# Generated by Django 3.2.3 on 2021-05-31 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('operation', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bar.drink')),
            ],
        ),
    ]
