# Generated by Django 3.2.3 on 2021-06-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation',
            field=models.CharField(choices=[('a', 'arrive'), ('s', 'sale')], default='a', max_length=1),
        ),
    ]
