# Generated by Django 3.2.3 on 2021-05-31 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='id',
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('operation', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bar.drink')),
            ],
        ),
    ]
